interface Env{DB:D1Database;RAZORPAY_WEBHOOK_SECRET?:string;RAZORPAY_STARTER_PLAN_ID?:string;RAZORPAY_PRO_PLAN_ID?:string}
type Sub={id?:string;plan_id?:string;customer_id?:string;status?:string;current_start?:number|null;current_end?:number|null;notes?:Record<string,unknown>|unknown[]}
type Event={event?:string;created_at?:number;payload?:{subscription?:{entity?:Sub}}}
const json=(body:unknown,status=200,h:HeadersInit={})=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8",...h}})
const rid=()=>`req_${crypto.randomUUID().replaceAll("-","")}`
const hex=(b:ArrayBuffer)=>Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("")
async function hmac(secret:string,body:string){const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return hex(await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(body)))}
const eq=(a:string,b:string)=>{if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
const isSub=(e:string)=>e.startsWith("subscription.")
const isAct=(e:string)=>e==="subscription.activated"||e==="subscription.resumed"
const isRenew=(e:string)=>e==="subscription.charged"
const isPause=(e:string)=>e==="subscription.paused"
const isFree=(e:string)=>e==="subscription.halted"||e==="subscription.cancelled"||e==="subscription.completed"
const isPre=(e:string)=>e==="subscription.authenticated"||e==="subscription.pending"
function tierFor(env:Env,id:string):"starter"|"pro"|null{if(env.RAZORPAY_STARTER_PLAN_ID&&id===env.RAZORPAY_STARTER_PLAN_ID)return"starter";if(env.RAZORPAY_PRO_PLAN_ID&&id===env.RAZORPAY_PRO_PLAN_ID)return"pro";return null}
async function process(env:Env,eventId:string,event:Event){
 const et=String(event.event??"unknown");
 if(!isSub(et)){await env.DB.prepare("UPDATE razorpay_webhook_events SET status='ignored',processed_at=? WHERE event_id=?").bind(new Date().toISOString(),eventId).run();return}
 const s=event.payload?.subscription?.entity;if(!s?.id)throw new Error("Missing subscription entity id");
 const sid=s.id,pid=String(s.plan_id??""),rpc=s.customer_id?String(s.customer_id):null,notes=s.notes&&!Array.isArray(s.notes)?s.notes:{} as Record<string,unknown>,t=Number(event.created_at??0);
 const ex=await env.DB.prepare("SELECT customer_id,tier,status,updated_at,last_event_created_at,is_current FROM razorpay_subscriptions WHERE subscription_id=? LIMIT 1").bind(sid).first<{customer_id:string;tier:string;status:string;updated_at:string;last_event_created_at:number|null;is_current:number}>();
 const noted=typeof notes.momentum_customer_id==="string"?notes.momentum_customer_id:null,customer=ex?.customer_id??noted;if(isPre(et)&&!customer){await env.DB.prepare("UPDATE razorpay_webhook_events SET status='processed',processed_at=?,error_message=NULL WHERE event_id=?").bind(new Date().toISOString(),eventId).run();return}if(!customer)throw new Error("Missing momentum_customer_id mapping");
 const cur=await env.DB.prepare("SELECT subscription_id,tier,last_event_created_at,status FROM razorpay_subscriptions WHERE customer_id=? AND is_current=1 LIMIT 1").bind(customer).first<{subscription_id:string;tier:string;last_event_created_at:number|null;status:string}>();
 const mapped=tierFor(env,pid);let tier:"free"|"starter"|"pro"|null=null;if(isAct(et)||isRenew(et)||et==="subscription.updated")tier=mapped;if(isFree(et))tier="free";if(isPause(et))tier=ex&&["starter","pro","free"].includes(ex.tier)?ex.tier as "starter"|"pro"|"free":mapped;if((isAct(et)||et==="subscription.updated")&&!tier)throw new Error("Unknown Razorpay plan id");
 if(t>0&&ex?.last_event_created_at!=null&&t<ex.last_event_created_at){await env.DB.prepare("UPDATE razorpay_webhook_events SET status='ignored',processed_at=?,error_message=NULL WHERE event_id=?").bind(new Date().toISOString(),eventId).run();return}
 const curTime=cur?.last_event_created_at??0;if(t>0&&cur&&cur.subscription_id!==sid&&curTime>0&&t<curTime){await env.DB.prepare("UPDATE razorpay_webhook_events SET status='ignored',processed_at=?,error_message=NULL WHERE event_id=?").bind(new Date().toISOString(),eventId).run();return}
 const claimCurrent=(isAct(et)||isRenew(et)||et==="subscription.updated")&&(!cur||cur.subscription_id===sid||t>=curTime);if(claimCurrent&&cur?.subscription_id!==sid)await env.DB.prepare("UPDATE razorpay_subscriptions SET is_current=0 WHERE customer_id=? AND is_current=1").bind(customer).run();
 const now=new Date().toISOString(),flag=(claimCurrent||ex?.is_current===1)?1:0,status=String(s.status??et);
 await env.DB.prepare("INSERT INTO razorpay_subscriptions(subscription_id,customer_id,razorpay_customer_id,plan_id,tier,status,current_start,current_end,created_at,updated_at,last_event_created_at,is_current) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(subscription_id) DO UPDATE SET customer_id=excluded.customer_id,razorpay_customer_id=excluded.razorpay_customer_id,plan_id=excluded.plan_id,tier=excluded.tier,status=excluded.status,current_start=excluded.current_start,current_end=excluded.current_end,updated_at=excluded.updated_at,last_event_created_at=CASE WHEN excluded.last_event_created_at IS NOT NULL THEN excluded.last_event_created_at ELSE razorpay_subscriptions.last_event_created_at END,is_current=excluded.is_current").bind(sid,customer,rpc,pid,tier??"unknown",status,s.current_start??null,s.current_end??null,now,now,t>0?t:null,flag).run();
 if(isPause(et)&&cur?.subscription_id!==sid){await env.DB.prepare("UPDATE razorpay_webhook_events SET status='processed',processed_at=?,error_message=NULL WHERE event_id=?").bind(now,eventId).run();return}
 if((isAct(et)||isRenew(et)||et==="subscription.updated")&&flag===1)await env.DB.prepare("UPDATE customers SET tier=?,monthly_quota=(SELECT monthly_quota FROM plans WHERE tier=? AND active=1),rate_limit_per_minute=(SELECT rate_limit_per_minute FROM plans WHERE tier=? AND active=1),active=1 WHERE id=?").bind(tier,tier,tier,customer).run();
 else if(isPause(et)&&flag===1)await env.DB.prepare("UPDATE customers SET active=0 WHERE id=?").bind(customer).run();
 else if(isFree(et)&&flag===1){await env.DB.prepare("UPDATE razorpay_subscriptions SET is_current=0 WHERE subscription_id=?").bind(sid).run();const repl=await env.DB.prepare("SELECT subscription_id,tier FROM razorpay_subscriptions WHERE customer_id=? AND subscription_id<>? AND status='active' ORDER BY COALESCE(last_event_created_at,0) DESC,updated_at DESC LIMIT 1").bind(customer,sid).first<{subscription_id:string;tier:string}>();if(repl&&["starter","pro"].includes(repl.tier)){await env.DB.prepare("UPDATE razorpay_subscriptions SET is_current=1 WHERE subscription_id=?").bind(repl.subscription_id).run();await env.DB.prepare("UPDATE customers SET tier=?,monthly_quota=(SELECT monthly_quota FROM plans WHERE tier=? AND active=1),rate_limit_per_minute=(SELECT rate_limit_per_minute FROM plans WHERE tier=? AND active=1),active=1 WHERE id=?").bind(repl.tier,repl.tier,repl.tier,customer).run()}else await env.DB.prepare("UPDATE customers SET tier='free',monthly_quota=(SELECT monthly_quota FROM plans WHERE tier='free' AND active=1),rate_limit_per_minute=(SELECT rate_limit_per_minute FROM plans WHERE tier='free' AND active=1),active=1 WHERE id=?").bind(customer).run()}
 await env.DB.prepare("UPDATE razorpay_webhook_events SET status='processed',processed_at=?,error_message=NULL WHERE event_id=?").bind(now,eventId).run()
}
async function webhook(req:Request,env:Env,id:string){const sec=env.RAZORPAY_WEBHOOK_SECRET;if(!sec)return json({error:{code:"BILLING_NOT_CONFIGURED",message:"Razorpay webhook secret is not configured",request_id:id}},503,{"x-request-id":id});const sig=req.headers.get("x-razorpay-signature")??"",eid=req.headers.get("x-razorpay-event-id")??"",body=await req.text(),want=await hmac(sec,body);if(!sig||!eq(want,sig))return json({error:{code:"INVALID_SIGNATURE",message:"Invalid Razorpay webhook signature",request_id:id}},401,{"x-request-id":id});if(!eid)return json({error:{code:"MISSING_EVENT_ID",message:"Missing x-razorpay-event-id header",request_id:id}},400,{"x-request-id":id});let e:Event;try{e=JSON.parse(body)}catch{return json({error:{code:"INVALID_JSON",message:"Webhook body must be valid JSON",request_id:id}},400,{"x-request-id":id})}const ca=Number(e.created_at??0);if(ca>0&&Math.abs(Date.now()/1000-ca)>300)return json({error:{code:"STALE_EVENT",message:"Webhook event is outside the five-minute replay window",request_id:id}},400,{"x-request-id":id});const et=String(e.event??"unknown"),c=await env.DB.prepare("INSERT OR IGNORE INTO razorpay_webhook_events(event_id,event_type,status,received_at,payload_sha256) VALUES(?,?,?,?,?)").bind(eid,et,"received",new Date().toISOString(),hex(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(body)))).run();if(c.meta.changes!==1){const old=await env.DB.prepare("SELECT status FROM razorpay_webhook_events WHERE event_id=? LIMIT 1").bind(eid).first<{status:string}>();if(old?.status==="failed")await env.DB.prepare("UPDATE razorpay_webhook_events SET status='received',error_message=NULL WHERE event_id=?").bind(eid).run();else return json({status:"ok",duplicate:true,request_id:id},200,{"x-request-id":id})}try{await process(env,eid,e)}catch(err){const msg=err instanceof Error?err.message:"Webhook processing failed";await env.DB.prepare("UPDATE razorpay_webhook_events SET status='failed',processed_at=?,error_message=? WHERE event_id=?").bind(new Date().toISOString(),msg.slice(0,500),eid).run();throw err}return json({status:"processed",request_id:id},200,{"x-request-id":id})}
export default{async fetch(req:Request,env:Env){const id=rid(),u=new URL(req.url);if(req.method==="OPTIONS")return new Response(null,{status:204});if(u.pathname==="/health"&&req.method==="GET")return json({status:"ok",service:"momentum-billing"},200,{"x-request-id":id});if(u.pathname==="/webhooks/razorpay"&&req.method==="POST")try{return await webhook(req,env,id)}catch(e){console.error("Razorpay webhook processing failed",e);return json({error:{code:"WEBHOOK_PROCESSING_FAILED",message:"Webhook processing failed; retry the event",request_id:id}},500,{"x-request-id":id})}return json({error:{code:"NOT_FOUND",message:"Route not found",request_id:id}},404,{"x-request-id":id})}}